# Invalid values will be treated as default values
# If an invalid configuration file is detected, it will be automatically backed-up and regenerated

# Modes: Instant, Effect
# Instant: Will instantly heal the player to full health
# Effect: Will apply an effect to the player with specified amplifier and duration (configure below)
mode: Effect

# Below only applies when mode is set to Effect
effect:
  # Effects: Instant-Health or Regeneration
  type: Regeneration
  duration: 3 # (in seconds)
  amplifier: 4
  particles: false

# When the WorldGuard hook is activated, the plugin will add a custom flag named "heal-on-kill".
# The plugin's function will only be active if a region has this flag set to "allow" (It will be "deny" by default in a region)
# Changes only apply after server restart
worldguard-hook: true