name: HealOnKill
version: '${project.version}'
main: etc.soap.healonkill.HealOnKill
api-version: 1.19
softdepend: [ WorldGuard ]
authors: [ Soap ]

commands:
  healonkill:
    description: HealOnKill Commands
