name: HealOnKill
version: '${project.version}'
main: etc.soap.healonkill.HealOnKill
api-version: 1.21
softdepend: [ WorldGuard ]
authors: [ Soapdev ]

commands:
  healonkill:
    description: HealOnKill Commands
